#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     color,          sensorCOLORFULL)
#pragma config(Sensor, S4,     IRSeeker,          sensorI2CCustom)
#pragma config(Motor,  motorB,          rightTread,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftTread,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           RMRobotics Autonomous Mode Code
//
// Program for autonomous portion of 2012-2013 FTC game: Ring It Up
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-irseeker-v1.h" //Include driver for ir seeker

typedef struct {
	// Keep track of left and right tread speeds
	int leftTreadSpeed;
	int rightTreadSpeed;

	// Direction of IR beacon
	int IRBeaconDir;

	// Color of floor
	int floorColor;

	// State of touch sensor
	int touched;
} State;

void getLatestInput(State *state);
void handleIRInputs(State *state);
void handleColorInputs(State *state);
void handleTouchInputs(State *state);
void updateAllMotors(State *state);

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// Detect IR Beacon and score pre-loaded ring on the appropiate peg
//
// Documentation for IR seeker v1 can be found in sample programs direcctory
// Help in using the IR seeker can also be found here:
// http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FTC/FTC_Documents/Using_the_IR_Seeker.pdf
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  State currentState;
  memset(&currentState, 0, sizeof(State));

  //waitForStart(); // Wait for the beginning of autonomous phase.

  while (currentState.IRBeaconDir != 8)
  {
  	getLatestInput(&currentState);
  	handleIRInputs(&currentState);
  	updateAllMotors(&currentState);
  }

  while (currentState.touched != 1)
  {
  	getLatestInput(&currentState);
  	handleColorInputs(&currentState);
  	handleTouchInputs(&currentState);
  	updateAllMotors(&currentState);
	}
}

void getLatestInput(State *state)
{
	state->IRBeaconDir = HTIRSreadDir(IRSeeker);
	state->floorColor = SensorValue[color];
	state->touched = SensorValue[touch];
}

void handleIRInputs(State *state)
{
	if (state->IRBeaconDir == 8) {
		state->leftTreadSpeed = 0;
		state->rightTreadSpeed = 0;
	} else {
		state->leftTreadSpeed = 100;
		state->rightTreadSpeed = 100;
	}
}

void handleColorInputs(State *state)
{
	if (SensorValue[color] == WHITECOLOR) {
		state->leftTreadSpeed = 50;
		state->rightTreadSpeed = 0;
	} else {
		state->leftTreadSpeed = 0;
		state->rightTreadSpeed = 50;
	}
}

void handleTouchInputs(State *state)
{
	if (SensorValue[touch] == 1) {
		state->leftTreadSpeed = 0;
		state->rightTreadSpeed = 0;
	}
}

void updateAllMotors(State *state)
{
	motor[leftTread] = state->leftTreadSpeed;
	motor[rightTread] = state->rightTreadSpeed;
}
