#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     front,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     back,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    wrist,                tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define ARMSPEED 50
#define DRIVESPEED 100
#define LIFTSPEED 100

typedef struct {
	int motorLeftSpeed;
	int motorRightSpeed;
	int motorFrontSpeed;
	int motorBackSpeed;
	int armSpeed;
	int liftSpeed;
} State;

void handleArmInputs(State *state);
void handleDriveInputs(State *state);
void drive(State *state, string dir);
void handleLiftInputs(State *state);
void updateState(State *state);

task main()
{
	State currentState;
	// Initialize everything in the current state to 0.
	memset(&currentState, 0, sizeof(currentState));

	while(true) {

		getJoystickSettings(joystick);

		handleDriveInputs(&currentState);
		handleLiftInputs(&currentState);
		handleArmInputs(&currentState);

		// TODO? See if new state makes sense?

	  updateState(&currentState);
	}
}

void handleDriveInputs(State *state)
{
	string dir = "";
	int wheels_x1 = 0;
	int wheels_y1 = 0;
	wheels_x1 = joystick.joy1_x2; //x-value = left-right joystick movement
	wheels_y1 = joystick.joy1_y2; //y-value = up-down joystick movmeent
	float tan_line_updown = wheels_x1+10;
	float tan_line_leftright = wheels_x1-10;

	if (abs(wheels_x1) > 10 && abs(wheels_y1) > 10) { //If in deadzone, ignore movement - no need to run useless code
		if (wheels_x1 > 0) {				//Must be either Forward, Right Forward Swing, Right Point, Right Backward Swing, or Backward
			//!IMPORTANT: Code works by order, so code CANNOT be merged unless order is followed
			if (wheels_y1 >= tan_line_updown) {					 //Forward
				dir="fwd";
			}else if (wheels_y1 >= tan_line_leftright) {	 //Diagonal Right Forward
				dir="dfr";
			} else if (wheels_y1 >= -tan_line_leftright) {					//Point Turn Right
				dir="rht";
			} else if (wheels_y1 >= -tan_line_updown) {					 //Diagonal Right Backward
				dir="lft";
			} else {					//Backward
				dir="bwd";
			}
		} else {				//Must be either Forward, Left Forward Swing, Left Point, Left Backward Swing, or Backward
			//!IMPORTANT: Code works by order, so code CANNOT be merged unless order is followed
			if (wheels_y1 >= -tan_line_leftright) {					 //Forward
				dir="fwd";
			}else if (wheels_y1 >= -tan_line_updown) {					//Diagonal Left Forward
				dir="dfl";
			} else if (wheels_y1 >= tan_line_updown) {					//Point Turn Left
				dir="lft";
			} else if (wheels_y1 >= tan_line_leftright) {					 //Diagonal Left Backward
				dir="dbl";
			} else {					//Backward
				dir="bwd";
			}
		}
	} else {		 //Joystick is in dead zone - set powers to zero
		dir="";
	}

	if(joy1Btn(3) == 1) {
		dir="spl";
	} else if(joy1Btn(1) == 1) {
		dir="spr";
	}

	drive(state, dir);
}

void drive(State *state, string dir)
{
	/*
	DIRECTION PARAMETER: (cw/ccw are determined from perspective of robot's center
	fwd = forward								move left motor cw, right motor ccw
	bwd = backward							move left motor ccw, right motor cw
	lft = left									move front motor cw, back motor ccw
	rht = right									move front motor ccw, back motor cw
	dfl = diagonal fwd left			move front motor ccw, back motor cw, left motor cw, right motor ccw
	dfr = diagonal fwd right		move front motor cw, back motor ccw, left motor cw, right motor ccw
	dbl = diagonal bwd left			move front motor ccw, back motor cw, left motor ccw, right motor cw
	dbr = diagonal bwd right		move front motor cw, back motor ccw, left motor ccw, right motor cw
	spl = spin left							move all motors ccw
	spr = spin right						move all motors cw
	*/
	if (strcmp(dir, "fwd") == 0) {
		state->motorFrontSpeed = 0;
		state->motorBackSpeed = 0;
		state->motorLeftSpeed = DRIVESPEED;
		state->motorRightSpeed = -DRIVESPEED;
	} else if (strcmp(dir, "bwd") == 0) {
		state->motorFrontSpeed = 0;
		state->motorBackSpeed = 0;
		state->motorLeftSpeed = -DRIVESPEED;
		state->motorRightSpeed = DRIVESPEED;
	} else if (strcmp(dir, "lft") == 0) {
		state->motorFrontSpeed = DRIVESPEED;
		state->motorBackSpeed = -DRIVESPEED;
		state->motorLeftSpeed = 0;
		state->motorRightSpeed = 0;
	} else if (strcmp(dir, "rht") == 0) {
		state->motorFrontSpeed = -DRIVESPEED;
		state->motorBackSpeed = DRIVESPEED;
		state->motorLeftSpeed = 0;
		state->motorRightSpeed = 0;
	} else if (strcmp(dir, "dfl") == 0) {
		state->motorFrontSpeed = -DRIVESPEED;
		state->motorBackSpeed = DRIVESPEED;
		state->motorLeftSpeed = DRIVESPEED;
		state->motorRightSpeed = -DRIVESPEED;
	} else if (strcmp(dir, "dfr") == 0) {
		state->motorFrontSpeed = DRIVESPEED;
		state->motorBackSpeed = -DRIVESPEED;
		state->motorLeftSpeed = DRIVESPEED;
		state->motorRightSpeed = -DRIVESPEED;
	} else if (strcmp(dir, "dbl") == 0) {
		state->motorFrontSpeed = -DRIVESPEED;
		state->motorBackSpeed = DRIVESPEED;
		state->motorLeftSpeed = -DRIVESPEED;
		state->motorRightSpeed = DRIVESPEED;
	} else if (strcmp(dir, "dbr") == 0) {
		state->motorFrontSpeed = DRIVESPEED;
		state->motorBackSpeed = -DRIVESPEED;
		state->motorLeftSpeed = -DRIVESPEED;
		state->motorRightSpeed = DRIVESPEED;
	} else if (strcmp(dir, "spl") == 0) {
		state->motorFrontSpeed = -DRIVESPEED;
		state->motorBackSpeed = -DRIVESPEED;
		state->motorLeftSpeed = -DRIVESPEED;
		state->motorRightSpeed = -DRIVESPEED;
	} else if (strcmp(dir, "spr") == 0) {
		state->motorFrontSpeed = DRIVESPEED;
		state->motorBackSpeed = DRIVESPEED;
		state->motorLeftSpeed = DRIVESPEED;
		state->motorRightSpeed = DRIVESPEED;
	} else {
		state->motorFrontSpeed = 0;
		state->motorBackSpeed = 0;
		state->motorLeftSpeed = 0;
		state->motorRightSpeed = 0;
	}
}

void handleArmInputs(State *state)
{
	if(joy1Btn(4) == 1)	{
		state->armSpeed = ARMSPEED;
	}
	else if(joy1Btn(2) == 1) {
		state->armSpeed = -ARMSPEED;
	}
	else {
		state->armSpeed = 0;
	}
}

void handleLiftInputs(State *state) {
	if(joy1_TopHat == 0) {
		state->liftSpeed = LIFTSPEED;
	} else if(joy1_TopHat == 4) {
	  state->liftSpeed = -LIFTSPEED;
	} else {
	  state->liftSpeed = 0;
	}
}

void updateState(State *state)
{
	motor[front] = state->motorFrontSpeed;
	motor[back] = state->motorBackSpeed;
	motor[left] = state->motorLeftSpeed;
	motor[right] = state->motorRightSpeed;
	motor[arm] = state->armSpeed;
	motor[lift] = state->liftSpeed;
}
