
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift3,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    horiz,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    vert1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    vert2,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           RMRobotics Autonomous Mode Code
//
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-gyro.h"

#define WRISTSPEED .3

//AUTONOMOUS VALUES
#define PAUSE_ONE 250


typedef struct {
	// Keep track of left and right tread speeds
	int leftTreadSpeed;
	int rightTreadSpeed;

	// Keep track of wrist servos' positions
	float horizPos; // (0 - 243)
	float vert1Pos; // (0 - 247)
	float vert2Pos; // (0 - 227)

	// Keep track of lift speed
	int liftSpeed;
	int returnSpeed;

} State;


void updateAllMotors(State *state);
void showDiagnostics(State *state);

void Fwd(State state, int length);
void Bwd(State state, int length);
void ResetTreads(State state, int length);
void leftTurn(State state, int angle);
void rightTurn(State state, int angle);
void raiseLift(State state, int length);
void lowerLift(State state, int length);

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  servo[horiz] = 0;
  servo[vert1] = 225;
  servo[vert2] = 220;

  // Disable joystick driver's diagnostics display to free up nxt screen for our own diagnostics diplay
	disableDiagnosticsDisplay();

  return;
}

task main()
{
  initializeRobot();

  // Initialize state values
  State currentState;
  memset(&currentState, 0, sizeof(currentState));
  currentState.vert2Pos = 220;
  currentState.vert1Pos = 225;



  /*
  wait1Msec(milliseconds)
	leftTreadSpeed (-100 -> 100)
	rightTreadSpeed (-100 -> 100)

  horizPos (0-243)
  vert1Pos (0-247)
  vert2Pos (0-227)

  up: liftSpeed (100) returnSpeed (10)
  dn: liftSpeed (10)  returnSpeed (100)
*/

  //!START FROM WALL

  //waitForStart();   // wait for start of autonomous phase

	HTGYROstartCal(HTGYRO);

  Fwd(currentState, 1000);
  Bwd(currentState, 1000);
  leftTurn(currentState, 90);
  rightTurn(currentState, 90);
  raiseLift(currentState, 750);
  lowerLift(currentState, 600);


  //reset
  memset(&currentState, 0, sizeof(currentState));
  currentState.vert2Pos = 220;
  currentState.vert1Pos = 225;
  updateAllMotors(&currentState);
}


void Fwd(State state, int length)
{
	state.leftTreadSpeed = 100;
	state.rightTreadSpeed = 100;
	updateAllMotors(&state);
	showDiagnostics(&state);
	wait1Msec(length);
	ResetTreads(state, PAUSE_ONE);
}
void Bwd(State state, int length)
{
	state.leftTreadSpeed = -100;
	state.rightTreadSpeed = -100;
	updateAllMotors(&state);
	showDiagnostics(&state);
	wait1Msec(length);
	ResetTreads(state, PAUSE_ONE);
}
void ResetTreads(State state, int length)
{
	state.leftTreadSpeed = 0;
	state.rightTreadSpeed = 0;
	state.liftSpeed = 0;
	state.returnSpeed = 0;
	updateAllMotors(&state);
	showDiagnostics(&state);
	wait1Msec(length);
}
void leftTurn(State state, int angle)
{
	float heading = 0;
	float rotSpeed = 0;
	state.leftTreadSpeed = 100;
	state.rightTreadSpeed = -100;
	updateAllMotors(&state);
	showDiagnostics(&state);

	time1[T1] = 0;

	while (heading < angle) {
		while (time1[T1] < 20) {
			wait1Msec(1);
		}

		time1[T1]=0;

		rotSpeed = HTGYROreadRot(HTGYRO);
		if (rotSpeed < 0) {
			rotSpeed = rotSpeed * -1;
		}
		heading += rotSpeed * 0.02;
	}
	ResetTreads(state, PAUSE_ONE);
}
void rightTurn(State state, int angle)
{
	float heading = 0;
	float rotSpeed = 0;
	state.leftTreadSpeed = -100;
	state.rightTreadSpeed = 100;
	updateAllMotors(&state);
	showDiagnostics(&state);

	time1[T1]=0;

	while (heading < angle) {
		while (time1[T1] < 20) {
			wait1Msec(1);
		}

		time1[T1]=0;

		rotSpeed = HTGYROreadRot(HTGYRO);
		if (rotSpeed < 0) {
			rotSpeed = rotSpeed * -1;
		}
		heading += rotSpeed * 0.02;
	}
	ResetTreads(state, PAUSE_ONE);
}
void raiseLift(State state, int length)
{
	state.liftSpeed = 100;
	state.returnSpeed = 10;
	updateAllMotors(&state);
	wait1Msec(length);
	ResetTreads(state, PAUSE_ONE);
}
void lowerLift(State state, int length)
{
	state.liftSpeed = 10;
	state.returnSpeed = 100;
	updateAllMotors(&state);
	wait1Msec(length);
	ResetTreads(state, PAUSE_ONE);
}




void updateAllMotors(State *state)
{
	motor[leftTread] = state->leftTreadSpeed;
	motor[rightTread] = state->rightTreadSpeed;
	motor[lift] = state->liftSpeed;
	motor[lift2] = state->liftSpeed;
	motor[lift3] = state->returnSpeed;
	servo[horiz] = state->horizPos;
	servo[vert1] = state->vert1Pos;
	servo[vert2] = state->vert2Pos;
}

void showDiagnostics(State *state)
{
	//create label
	string sWristHorizPos = "horiz = ";
	string sWristVert1Pos = "vert1 = ";
	string sWristVert2Pos = "vert2 = ";

	//store variable in a string
	string string1 = state->horizPos;
	string string2 = state->vert1Pos;
	string string3 = state->vert2Pos;

	//concat variable with label
	strcat(sWristHorizPos, string1);
	strcat(sWristVert1Pos, string2);
	strcat(sWristVert2Pos, string3);

	eraseDisplay();

	//display label and value
	nxtDisplayTextLine(1, sWristHorizPos);
	nxtDisplayTextLine(3, sWristVert1Pos);
	nxtDisplayTextLine(5, sWristVert2Pos);
}
