#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTGYRO,              sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lift3,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    wristHoriz,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    wristVert1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    wristVert2,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-gyro.h"

  /*
  wait1Msec(milliseconds)
	leftTreadSpeed (-100 -> 100) //facing front, NOT FROM FRONT
	rightTreadSpeed (-100 -> 100) //facing front, NOT FROM FRONT

  wristHorizPos (0-243)
  wristVert1Pos (0-247) //default 22
  wristVert2Pos (0-227) //default 226

  up: liftSpeed (100) returnSpeed (10)
  dn: liftSpeed (10)  returnSpeed (100)
*/

#define WRISTSPEED .3

//AUTONOMOUS VALUES
//#define LIFT_UP 750
#define PAUSE_ONE 1000
#define WRISTONEPOSINCR 175 //increase
#define WRISTTWOPOSINCR 72 //decrease
#define FORWARD_ONE 3500
//PAUSE_ONE
//#define LIFT_LOWER 500
#define WRISTONEPOS 22 //decrease
#define WRISTTWOPOS 226 //increase
//PAUSE_ONE
#define BACKWARD_ONE 750
//PAUSE_ONE
//TURN 135 LEFT
#define FORWARD_TWO 1200


typedef struct {
	// Keep track what buttons were previously pressed so that
	// we can figure out whether their state changed.
	short old_joy1_Buttons;
	short old_joy2_Buttons;

	// Keep track of left and right tread speeds
	int leftTreadSpeed;
	int rightTreadSpeed;

	// Keep track of wrist servos' positions
	float wristHorizPos; // (0 - 243)
	float wristVert1Pos; // (0 - 247)
	float wristVert2Pos; // (0 - 227)

	// Keep track of lift speed
	int liftSpeed;
	int returnSpeed;

} State;


void verifyCommands(State *state);
void updateAllMotors(State *state);
void showDiagnostics(State *state);

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  servo[wristHoriz] = 0;
  servo[wristVert1] = 22;
  servo[wristVert2] = 226;

  // Disable joystick driver's diagnostics display to free up nxt screen for our own diagnostics diplay
	disableDiagnosticsDisplay();

  return;
}


task main()
{
  initializeRobot();

  // Initialize state values
  State currentState;
  memset(&currentState, 0, sizeof(currentState));
  currentState.wristVert2Pos = 226;
  currentState.wristVert1Pos = 22;
	updateAllMotors(&currentState);

  //!START FROM CORNER FACING PEG


  //waitForStart();   // wait for start of AUTONOMOUS phase

	HTGYROstartCal(HTGYRO);
/*
	//raise lift
  nxtDisplayTextLine(1, "raising");
  currentState.liftSpeed = 100;
  currentState.returnSpeed = 10;
  updateAllMotors(&currentState);
  wait1Msec(LIFT_UP);

  nxtDisplayTextLine(1, "pausing");
  currentState.leftTreadSpeed = 0;
  currentState.rightTreadSpeed = 0;
  currentState.liftSpeed = 0;
  currentState.returnSpeed = 0;
  updateAllMotors(&currentState);
  wait1Msec(PAUSE_ONE);
*/
	//raise hand
	nxtDisplayTextLine(1, "DO YOU EVEN LIFT");
	currentState.wristVert1Pos = WRISTONEPOSINCR;
	currentState.wristVert2Pos = WRISTTWOPOSINCR;
	updateAllMotors(&currentState);

	//turn left 45
	nxtDisplayTextLine(1, "turning left");
	float heading = 0;
	float rotSpeed = 0;
	float angle = 45;
	currentState.leftTreadSpeed = 100;
	currentState.rightTreadSpeed = -100;
	updateAllMotors(&currentState);
	showDiagnostics(&currentState);

	time1[T1] = 0;

	while (heading < angle) {
		while (time1[T1] < 20) {
			wait1Msec(1);
		}

		time1[T1]=0;

		rotSpeed = HTGYROreadRot(HTGYRO);
		if (rotSpeed < 0) {
			rotSpeed = rotSpeed * -1;
		}
		heading += rotSpeed * 0.02;
	}

  //drive forward
	nxtDisplayTextLine(1, "driving forward");
  currentState.leftTreadSpeed = 100;
  currentState.rightTreadSpeed = 100;
  updateAllMotors(&currentState);
  wait1Msec(FORWARD_ONE);

	nxtDisplayTextLine(1, "pausing");
  currentState.leftTreadSpeed = 0;
  currentState.rightTreadSpeed = 0;
  updateAllMotors(&currentState);
  wait1Msec(PAUSE_ONE);
/*
  //lower lift
  nxtDisplayTextLine(1, "lowering");
  currentState.liftSpeed = 10;
  currentState.returnSpeed = 100;
  updateAllMotors(&currentState);
  wait1Msec(LIFT_LOWER);
*/

	//lower hand
	nxtDisplayTextLine(1, "I DONT THINK SO");
	currentState.wristVert1Pos = WRISTONEPOS; //decrease
	currentState.wristVert2Pos = WRISTTWOPOS; //increase

	nxtDisplayTextLine(1, "pausing");
  currentState.leftTreadSpeed = 0;
  currentState.rightTreadSpeed = 0;
  currentState.liftSpeed = 0;
  currentState.returnSpeed = 0;
  updateAllMotors(&currentState);
  wait1Msec(PAUSE_ONE);

  //drive backwards
	nxtDisplayTextLine(1, "driving backward");
  currentState.leftTreadSpeed = -100;
  currentState.rightTreadSpeed = -100;
  updateAllMotors(&currentState);
  wait1Msec(BACKWARD_ONE);

  nxtDisplayTextLine(1, "pausing");
  currentState.leftTreadSpeed = 0;
  currentState.rightTreadSpeed = 0;
  updateAllMotors(&currentState);
  wait1Msec(PAUSE_ONE);

  //135 degree turn so facing dispenser
  nxtDisplayTextLine(1, "turning left");
	heading = 0;
	rotSpeed = 0;
	angle = 135;
	currentState.leftTreadSpeed = 100;
	currentState.rightTreadSpeed = -100;
	updateAllMotors(&currentState);
	showDiagnostics(&currentState);

	time1[T1] = 0;

	while (heading < angle) {
		while (time1[T1] < 20) {
			wait1Msec(1);
		}

		time1[T1]=0;

		rotSpeed = HTGYROreadRot(HTGYRO);
		if (rotSpeed < 0) {
			rotSpeed = rotSpeed * -1;
		}
		heading += rotSpeed * 0.02;
	}

	nxtDisplayTextLine(1, "pausing");
  currentState.leftTreadSpeed = 0;
  currentState.rightTreadSpeed = 0;
  updateAllMotors(&currentState);
  wait1Msec(PAUSE_ONE);

  //drive forward to dispenser
	nxtDisplayTextLine(1, "driving forward");
  currentState.leftTreadSpeed = 100;
  currentState.rightTreadSpeed = 100;
  updateAllMotors(&currentState);
  wait1Msec(FORWARD_TWO);



  //reset
  memset(&currentState, 0, sizeof(currentState));
  currentState.wristVert2Pos = 226;
  currentState.wristVert1Pos = 22;
  updateAllMotors(&currentState);



  // Execute user inputs
  showDiagnostics(&currentState);

}

void verifyCommands(State *state)
{
	// If the projected servo values aren't within the servos' ranges,
	// stay at the servos' current positions.

	// Servo Ranges
	// Horiz Servo: 0 - 243
	// 1st Vert Servo: 0 - 247
	// 2nd Vert Servo: 0 - 227

	if (state->wristHorizPos > 243 || state->wristHorizPos < 0) {
		state->wristHorizPos = ServoValue[wristHoriz];
	}

	if (state->wristVert1Pos > 247 || state->wristVert2Pos < 0
	 || state->wristVert2Pos > 227 || state->wristVert2Pos < 0) {
		state->wristVert1Pos = ServoValue[wristVert1];
		state->wristVert2Pos = ServoValue[wristVert2];
	}
}

void updateAllMotors(State *state)
{
	motor[leftTread] = state->leftTreadSpeed;
	motor[rightTread] = state->rightTreadSpeed;
	motor[lift] = state->liftSpeed;
	motor[lift2] = state->liftSpeed;
	motor[lift3] = state->returnSpeed;
	servo[wristHoriz] = state->wristHorizPos;
	servo[wristVert1] = state->wristVert1Pos;
	servo[wristVert2] = state->wristVert2Pos;
}

void showDiagnostics(State *state)
{
	//create label
	string sWristHorizPos = "wristHoriz = ";
	string sWristVert1Pos = "wristVert1 = ";
	string sWristVert2Pos = "wristVert2 = ";

	//store variable in a string
	string string1 = state->wristHorizPos;
	string string2 = state->wristVert1Pos;
	string string3 = state->wristVert2Pos;

	//concat variable with label
	strcat(sWristHorizPos, string1);
	strcat(sWristVert1Pos, string2);
	strcat(sWristVert2Pos, string3);

	eraseDisplay();

	//display label and value
	nxtDisplayTextLine(1, sWristHorizPos);
	nxtDisplayTextLine(3, sWristVert1Pos);
	nxtDisplayTextLine(5, sWristVert2Pos);
}
