#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S4,     HTIRS,          sensorI2CCustom)
#pragma config(Motor,  motorB,          rightTread,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftTread,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           RMRobotics Autonomous Mode Code
//
// Program for autonomous portion of 2012-2013 FTC game: Ring It Up
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-irseeker-v1.h" //Include driver for ir seeker

typedef struct {
	// Keep track of left and right tread speeds
	int leftTreadSpeed;
	int rightTreadSpeed;

	// Direction of IR beacon
	int dir;
} State;

void getLatestInput(State *state);
void handleDriveInputs(State *state);
void updateAllMotors(State *state);

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// Detect IR Beacon and score pre-loaded ring on the appropiate peg
//
// Documentation for IR seeker v1 can be found in sample programs direcctory
// Help in using the IR seeker can also be found here:
// http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FTC/FTC_Documents/Using_the_IR_Seeker.pdf
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  State currentState;
  memset(&currentState, 0, sizeof(State));

  //waitForStart(); // Wait for the beginning of autonomous phase.

  while (currentState.dir != 8)
  {
  	getLatestInput(&currentState);
  	handleDriveInputs(&currentState);
  	updateAllMotors(&currentState);
  }
}

void getLatestInput(State *state)
{

	state->dir = HTIRSreadDir(HTIRS);
	//HTIRSreadAllStrength(HTIRS, dcS1, dcS2, dcS3, dcS4, dcS5);
}

void handleDriveInputs(State *state)
{
	if (state->dir == 8) {
		state->leftTreadSpeed = 0;
		state->rightTreadSpeed = 0;
	} else {
		state->leftTreadSpeed = -100;
		state->rightTreadSpeed = -100;
	}
}

void updateAllMotors(State *state)
{
	motor[leftTread] = state->leftTreadSpeed;
	motor[rightTread] = state->rightTreadSpeed;
}
